kind: pipeline
type: docker
name: default

workspace:
  path: /drone/src
  
steps:
- name: buildProject
  image: mcr.microsoft.com/dotnet/aspnet:7.0
  pull: if-not-exists
  commands:
  - /bin/bash
  - chmod a+x build.sh
  - sh build.sh
