kind: pipeline
type: docker
name: default

steps:
- name: pullSdk
  image: mcr.microsoft.com/dotnet/sdk:7.0

- name: buildProject
  image: mcr.microsoft.com/dotnet/sdk:7.0
  commands:
  - dotnet build
  - dotnet publish
  - dotnet droneService.dll
