kind: pipeline
type: docker
name: default

steps:
- name: test
  image: mcr.microsoft.com/dotnet/aspnet:7.0
  pull: never
  commands:
  - build -t droneservice .
  - run -p 8080:8080 -d -name droneService1 droneservice
